spring:    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/product?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
